import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import Head from 'next/head'
import Link from 'next/link';
import { useEffect, useState } from 'react'
import Message from '../components/message'
import { db } from '../utils/firebase'

import Skeleton from 'react-loading-skeleton'
import 'react-loading-skeleton/dist/skeleton.css'

export default function Home() {
  // create a state with all the posts
  const [allPosts, setAllPosts] = useState({});

  const getPosts = async () => {
    setAllPosts({
      data: [],
      loading: true
    })
    const collectionRef = collection(db, 'posts');
    const q = query(collectionRef, orderBy('timestamp', 'desc'));
    const unsubscribe = await onSnapshot(q, (snapshot) => {
      setAllPosts({
        data: snapshot.docs.map((doc) => ({
          id: doc.id,
          ...doc.data()
        })),
        loading: false
      })
    });
    return unsubscribe;
  }

  useEffect(() => {
    getPosts();
    console.log(allPosts);
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='my-12 text-lg font-medium'>
        <h2>See what other people are saying</h2>
        {
          allPosts.loading && (
            <div className='mt-4'>
              <Skeleton style={{marginBottom: '20px'}} height={'200px'} />
              <Skeleton style={{marginBottom: '20px'}} height={'200px'} />
              <Skeleton style={{marginBottom: '20px'}} height={'200px'} />
            </div>
          )
        }
        {
          allPosts.data?.map((post) => (
            <Message key={post.id} {...post}>
              <Link href={{pathname: `/${post.id}`, query: {...post}}}>
                <button>
                  comments
                </button>
              </Link>
            </Message>
          ))
        }
      </div>
    </div>
  )
}
