import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Message from '../components/message'
import { db } from '../utils/firebase'

export default function Home() {
  // create a state with all the posts
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, 'posts');
    const q = query(collectionRef, orderBy('timestamp', 'desc'));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({
        id: doc.id,
        ...doc.data()
      })));
    });
    return unsubscribe;
  }

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='my-12 text-lg font-medium'>
        <h2>See what other people are saying</h2>
        {
          allPosts.map((post) => (
            <Message key={post.id} {...post}></Message>
          ))
        }
      </div>
    </div>
  )
}
